name: Package Integration Testing

on:
  push:
    branches: [ main ]
  create:
    tags:
      - v*

jobs:
  # package test
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Display Testing Details
        run: |
          echo "Running SDK Test before publishing release"
          echo "Release tag: ${{ github.ref_name }}"

      - uses: Eppo-exp/sdk-test-data/.github/actions/test-server-package@main
        name: "Test Eppo-powered PHP server"
        with:
          platform: 'linux'
          sdk_name: 'eppo/php-sdk'
          sdk_ref: ${{ github.ref_name }}
          sdk_relay_dir: 'php-sdk-relay'
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          sdk_testing_project_id: ${{ vars.SDK_TESTING_PROJECT_ID }}
          sdk_testing_region: ${{ vars.SDK_TESTING_REGION }}
